CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "solstice_comment_like" (
	"commentId" integer NOT NULL,
	"userId" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "solstice_comment_like_commentId_userId_pk" PRIMARY KEY("commentId","userId")
);
--> statement-breakpoint
CREATE TABLE "solstice_comment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_comment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"practiceSlug" text,
	"userId" text NOT NULL,
	"parentId" integer,
	"body" text NOT NULL,
	"tag" text,
	"atSeconds" integer,
	"visibility" text DEFAULT 'circle' NOT NULL,
	"pinned" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "solstice_email_outbox" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_email_outbox_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"to" text NOT NULL,
	"subject" text NOT NULL,
	"text" text NOT NULL,
	"actionUrl" text,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "solstice_favorite" (
	"userId" text NOT NULL,
	"practiceSlug" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "solstice_favorite_userId_practiceSlug_pk" PRIMARY KEY("userId","practiceSlug")
);
--> statement-breakpoint
CREATE TABLE "solstice_membership" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_membership_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"plan" text NOT NULL,
	"status" text NOT NULL,
	"provider" text NOT NULL,
	"providerSubscriptionId" text,
	"trialEndsAt" timestamp with time zone,
	"currentPeriodEnd" timestamp with time zone NOT NULL,
	"cancelAtPeriodEnd" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "solstice_membership_userId_unique" UNIQUE("userId")
);
--> statement-breakpoint
CREATE TABLE "solstice_newsletter_subscriber" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_newsletter_subscriber_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"locale" varchar(8) NOT NULL,
	"source" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "solstice_newsletter_subscriber_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "solstice_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "solstice_practice_completion" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_practice_completion_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"practiceSlug" text NOT NULL,
	"minutes" integer NOT NULL,
	"programSlug" text,
	"programDay" integer,
	"completedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "solstice_practice" (
	"slug" text PRIMARY KEY NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"featured" boolean DEFAULT false NOT NULL,
	"title" jsonb NOT NULL,
	"summary" jsonb NOT NULL,
	"series" jsonb NOT NULL,
	"category" text NOT NULL,
	"intensityLevel" text NOT NULL,
	"intensityLabel" jsonb NOT NULL,
	"props" text NOT NULL,
	"durationMinutes" integer NOT NULL,
	"rating" real DEFAULT 0 NOT NULL,
	"reviewCount" integer DEFAULT 0 NOT NULL,
	"access" text NOT NULL,
	"previewSeconds" integer,
	"image" text NOT NULL,
	"imageAlt" jsonb NOT NULL,
	"poster" text,
	"instructorNote" jsonb,
	"focus" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"implements" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"chapters" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"videoProvider" text,
	"videoAssetId" text,
	"publishedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "solstice_program_enrollment" (
	"userId" text NOT NULL,
	"programSlug" text NOT NULL,
	"startedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "solstice_program_enrollment_userId_programSlug_pk" PRIMARY KEY("userId","programSlug")
);
--> statement-breakpoint
CREATE TABLE "solstice_push_subscription" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_push_subscription_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"endpoint" text NOT NULL,
	"p256dh" text NOT NULL,
	"auth" text NOT NULL,
	"locale" varchar(8) NOT NULL,
	"userAgent" text,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "solstice_push_subscription_endpoint_unique" UNIQUE("endpoint")
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"role" text DEFAULT 'member' NOT NULL,
	"practice_rhythm" text,
	"marketing_opt_in" boolean DEFAULT false NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_comment_like" ADD CONSTRAINT "solstice_comment_like_commentId_solstice_comment_id_fk" FOREIGN KEY ("commentId") REFERENCES "public"."solstice_comment"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_comment_like" ADD CONSTRAINT "solstice_comment_like_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_comment" ADD CONSTRAINT "solstice_comment_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_comment" ADD CONSTRAINT "solstice_comment_parentId_solstice_comment_id_fk" FOREIGN KEY ("parentId") REFERENCES "public"."solstice_comment"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_favorite" ADD CONSTRAINT "solstice_favorite_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_membership" ADD CONSTRAINT "solstice_membership_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_post" ADD CONSTRAINT "solstice_post_createdById_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_practice_completion" ADD CONSTRAINT "solstice_practice_completion_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_program_enrollment" ADD CONSTRAINT "solstice_program_enrollment_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_push_subscription" ADD CONSTRAINT "solstice_push_subscription_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "comment_practice_idx" ON "solstice_comment" USING btree ("practiceSlug","createdAt");--> statement-breakpoint
CREATE INDEX "comment_parent_idx" ON "solstice_comment" USING btree ("parentId");--> statement-breakpoint
CREATE INDEX "email_outbox_created_idx" ON "solstice_email_outbox" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "membership_status_idx" ON "solstice_membership" USING btree ("status");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "solstice_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "solstice_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "practice_completion_user_idx" ON "solstice_practice_completion" USING btree ("userId","completedAt");--> statement-breakpoint
CREATE INDEX "practice_status_idx" ON "solstice_practice" USING btree ("status");--> statement-breakpoint
CREATE INDEX "push_subscription_user_idx" ON "solstice_push_subscription" USING btree ("userId");