CREATE TABLE "solstice_category" (
	"kind" text NOT NULL,
	"slug" text NOT NULL,
	"name" jsonb NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"visible" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "solstice_category_kind_slug_pk" PRIMARY KEY("kind","slug")
);
--> statement-breakpoint
CREATE TABLE "solstice_practice_like" (
	"userId" text NOT NULL,
	"practiceSlug" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "solstice_practice_like_userId_practiceSlug_pk" PRIMARY KEY("userId","practiceSlug")
);
--> statement-breakpoint
CREATE TABLE "solstice_newsletter_issue" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_newsletter_issue_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"subject" jsonb NOT NULL,
	"body" jsonb NOT NULL,
	"recipients" integer DEFAULT 0 NOT NULL,
	"failed" integer DEFAULT 0 NOT NULL,
	"sentAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "solstice_membership_plan" (
	"id" text PRIMARY KEY NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"featured" boolean DEFAULT false NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"name" jsonb NOT NULL,
	"description" jsonb NOT NULL,
	"badge" jsonb NOT NULL,
	"features" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"price" numeric(14, 2) NOT NULL,
	"prices" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"intervalMonths" integer NOT NULL,
	"trialDays" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "solstice_setting" (
	"key" text PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "solstice_checkout" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"planId" text NOT NULL,
	"provider" text NOT NULL,
	"amount" numeric(14, 2) NOT NULL,
	"currency" text NOT NULL,
	"intervalMonths" integer NOT NULL,
	"trialDays" integer DEFAULT 0 NOT NULL,
	"renewal" boolean DEFAULT false NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"providerReference" text,
	"locale" varchar(8) NOT NULL,
	"nextPath" text DEFAULT '/practices' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"completedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "solstice_payment_event" (
	"provider" text NOT NULL,
	"eventId" text NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "solstice_payment_event_provider_eventId_pk" PRIMARY KEY("provider","eventId")
);
--> statement-breakpoint
CREATE TABLE "solstice_payment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_payment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text,
	"email" text NOT NULL,
	"checkoutId" text,
	"provider" text NOT NULL,
	"providerPaymentId" text NOT NULL,
	"planId" text NOT NULL,
	"kind" text NOT NULL,
	"amount" numeric(14, 2) NOT NULL,
	"currency" text NOT NULL,
	"status" text DEFAULT 'paid' NOT NULL,
	"refundedAmount" numeric(14, 2) DEFAULT 0 NOT NULL,
	"periodStart" timestamp with time zone NOT NULL,
	"periodEnd" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"refundedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "solstice_comment" ADD COLUMN "status" text DEFAULT 'approved' NOT NULL;--> statement-breakpoint
ALTER TABLE "solstice_membership" ADD COLUMN "renewalReminderFor" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "solstice_practice_like" ADD CONSTRAINT "solstice_practice_like_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_checkout" ADD CONSTRAINT "solstice_checkout_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_payment" ADD CONSTRAINT "solstice_payment_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "practice_like_slug_idx" ON "solstice_practice_like" USING btree ("practiceSlug");--> statement-breakpoint
CREATE INDEX "membership_plan_status_idx" ON "solstice_membership_plan" USING btree ("status");--> statement-breakpoint
CREATE INDEX "checkout_user_idx" ON "solstice_checkout" USING btree ("userId","createdAt");--> statement-breakpoint
CREATE UNIQUE INDEX "payment_provider_ref_idx" ON "solstice_payment" USING btree ("provider","providerPaymentId");--> statement-breakpoint
CREATE INDEX "payment_user_idx" ON "solstice_payment" USING btree ("userId","createdAt");--> statement-breakpoint
CREATE INDEX "payment_created_idx" ON "solstice_payment" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "comment_status_idx" ON "solstice_comment" USING btree ("status");