CREATE TABLE "solstice_conversation_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_conversation_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conversationId" integer NOT NULL,
	"author" text NOT NULL,
	"authorId" text,
	"body" text NOT NULL,
	"practiceSlug" text,
	"practiceAt" integer,
	"model" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "solstice_conversation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_conversation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kind" text NOT NULL,
	"userId" text,
	"visitorId" text,
	"clientKey" text,
	"guestName" text,
	"guestEmail" text,
	"topic" text,
	"subject" text DEFAULT '' NOT NULL,
	"status" text NOT NULL,
	"waitingSince" timestamp with time zone,
	"locale" varchar(8) NOT NULL,
	"lastMessageAt" timestamp with time zone DEFAULT now() NOT NULL,
	"memberReadAt" timestamp with time zone,
	"staffReadAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "solstice_guidance_waitlist" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_guidance_waitlist_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"planId" text NOT NULL,
	"userId" text NOT NULL,
	"notifiedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "solstice_membership_plan" ADD COLUMN "guidance" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "solstice_membership_plan" ADD COLUMN "guidancePlaces" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "solstice_conversation_message" ADD CONSTRAINT "solstice_conversation_message_conversationId_solstice_conversation_id_fk" FOREIGN KEY ("conversationId") REFERENCES "public"."solstice_conversation"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_conversation_message" ADD CONSTRAINT "solstice_conversation_message_authorId_user_id_fk" FOREIGN KEY ("authorId") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_conversation" ADD CONSTRAINT "solstice_conversation_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_guidance_waitlist" ADD CONSTRAINT "solstice_guidance_waitlist_planId_solstice_membership_plan_id_fk" FOREIGN KEY ("planId") REFERENCES "public"."solstice_membership_plan"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_guidance_waitlist" ADD CONSTRAINT "solstice_guidance_waitlist_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "conversation_message_conversation_idx" ON "solstice_conversation_message" USING btree ("conversationId","id");--> statement-breakpoint
CREATE INDEX "conversation_user_idx" ON "solstice_conversation" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "conversation_visitor_idx" ON "solstice_conversation" USING btree ("visitorId");--> statement-breakpoint
CREATE INDEX "conversation_queue_idx" ON "solstice_conversation" USING btree ("kind","status","waitingSince");--> statement-breakpoint
CREATE UNIQUE INDEX "guidance_waitlist_plan_user_idx" ON "solstice_guidance_waitlist" USING btree ("planId","userId");