CREATE TABLE "solstice_live_class_rsvp" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_live_class_rsvp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"classId" integer NOT NULL,
	"userId" text NOT NULL,
	"attended" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "solstice_live_class" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_live_class_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"status" text DEFAULT 'scheduled' NOT NULL,
	"title" jsonb NOT NULL,
	"description" jsonb NOT NULL,
	"instructorName" jsonb NOT NULL,
	"locationName" jsonb NOT NULL,
	"scheduledAt" timestamp with time zone NOT NULL,
	"durationMinutes" integer DEFAULT 60 NOT NULL,
	"joinUrl" text NOT NULL,
	"capacity" integer,
	"access" text DEFAULT 'members_only' NOT NULL,
	"replayPracticeSlug" text,
	"coverImage" text DEFAULT '/images/classes/kyoto-pavilion-stage.jpg' NOT NULL,
	"soundscapeDetails" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "solstice_live_class_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "solstice_live_class_rsvp" ADD CONSTRAINT "solstice_live_class_rsvp_classId_solstice_live_class_id_fk" FOREIGN KEY ("classId") REFERENCES "public"."solstice_live_class"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_live_class_rsvp" ADD CONSTRAINT "solstice_live_class_rsvp_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "live_class_rsvp_class_user_idx" ON "solstice_live_class_rsvp" USING btree ("classId","userId");--> statement-breakpoint
CREATE INDEX "live_class_rsvp_user_idx" ON "solstice_live_class_rsvp" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "live_class_scheduled_at_idx" ON "solstice_live_class" USING btree ("scheduledAt");--> statement-breakpoint
CREATE INDEX "live_class_status_idx" ON "solstice_live_class" USING btree ("status");--> statement-breakpoint
CREATE INDEX "live_class_slug_idx" ON "solstice_live_class" USING btree ("slug");