CREATE TABLE "solstice_member_note" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_member_note_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"instructorId" text NOT NULL,
	"body" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "solstice_member_onboarding" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_member_onboarding_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"experienceLevel" text DEFAULT 'beginner' NOT NULL,
	"primaryGoals" jsonb NOT NULL,
	"timeAvailable" text DEFAULT '30_mins' NOT NULL,
	"injuriesAndLimits" text,
	"completedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "solstice_member_onboarding_userId_unique" UNIQUE("userId")
);
--> statement-breakpoint
ALTER TABLE "solstice_member_note" ADD CONSTRAINT "solstice_member_note_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_member_note" ADD CONSTRAINT "solstice_member_note_instructorId_user_id_fk" FOREIGN KEY ("instructorId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_member_onboarding" ADD CONSTRAINT "solstice_member_onboarding_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "member_note_user_idx" ON "solstice_member_note" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "member_note_created_at_idx" ON "solstice_member_note" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "member_onboarding_user_idx" ON "solstice_member_onboarding" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "member_onboarding_level_idx" ON "solstice_member_onboarding" USING btree ("experienceLevel");