CREATE TABLE "solstice_coupon_redemption" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_coupon_redemption_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"couponId" integer NOT NULL,
	"userId" text NOT NULL,
	"checkoutId" text,
	"discountAmount" numeric(14, 2) DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "solstice_coupon" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_coupon_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(50) NOT NULL,
	"discountType" text DEFAULT 'percent' NOT NULL,
	"discountValue" numeric(14, 2) NOT NULL,
	"duration" text DEFAULT 'once' NOT NULL,
	"planId" text,
	"maxUses" integer,
	"usedCount" integer DEFAULT 0 NOT NULL,
	"expiresAt" timestamp with time zone,
	"active" boolean DEFAULT true NOT NULL,
	"description" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "solstice_coupon_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "solstice_gift_membership" (
	"id" text PRIMARY KEY NOT NULL,
	"code" varchar(50) NOT NULL,
	"purchaserUserId" text,
	"purchaserEmail" text NOT NULL,
	"purchaserName" text,
	"recipientEmail" text,
	"recipientName" text,
	"personalMessage" text,
	"months" integer NOT NULL,
	"planId" text NOT NULL,
	"checkoutId" text,
	"status" text DEFAULT 'active' NOT NULL,
	"redeemedByUserId" text,
	"redeemedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "solstice_gift_membership_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "solstice_referral" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_referral_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"referrerId" text NOT NULL,
	"referredUserId" text NOT NULL,
	"referralCode" varchar(50) NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"rewardedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "solstice_referral_referredUserId_unique" UNIQUE("referredUserId")
);
--> statement-breakpoint
ALTER TABLE "solstice_checkout" ADD COLUMN "couponCode" text;--> statement-breakpoint
ALTER TABLE "solstice_checkout" ADD COLUMN "discountAmount" numeric(14, 2) DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "solstice_checkout" ADD COLUMN "giftId" text;--> statement-breakpoint
ALTER TABLE "solstice_coupon_redemption" ADD CONSTRAINT "solstice_coupon_redemption_couponId_solstice_coupon_id_fk" FOREIGN KEY ("couponId") REFERENCES "public"."solstice_coupon"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_coupon_redemption" ADD CONSTRAINT "solstice_coupon_redemption_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_coupon_redemption" ADD CONSTRAINT "solstice_coupon_redemption_checkoutId_solstice_checkout_id_fk" FOREIGN KEY ("checkoutId") REFERENCES "public"."solstice_checkout"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_gift_membership" ADD CONSTRAINT "solstice_gift_membership_purchaserUserId_user_id_fk" FOREIGN KEY ("purchaserUserId") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_gift_membership" ADD CONSTRAINT "solstice_gift_membership_checkoutId_solstice_checkout_id_fk" FOREIGN KEY ("checkoutId") REFERENCES "public"."solstice_checkout"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_gift_membership" ADD CONSTRAINT "solstice_gift_membership_redeemedByUserId_user_id_fk" FOREIGN KEY ("redeemedByUserId") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_referral" ADD CONSTRAINT "solstice_referral_referrerId_user_id_fk" FOREIGN KEY ("referrerId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solstice_referral" ADD CONSTRAINT "solstice_referral_referredUserId_user_id_fk" FOREIGN KEY ("referredUserId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "coupon_redemption_coupon_idx" ON "solstice_coupon_redemption" USING btree ("couponId");--> statement-breakpoint
CREATE INDEX "coupon_redemption_user_idx" ON "solstice_coupon_redemption" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "coupon_code_idx" ON "solstice_coupon" USING btree ("code");--> statement-breakpoint
CREATE INDEX "coupon_active_idx" ON "solstice_coupon" USING btree ("active");--> statement-breakpoint
CREATE INDEX "gift_membership_code_idx" ON "solstice_gift_membership" USING btree ("code");--> statement-breakpoint
CREATE INDEX "gift_membership_purchaser_idx" ON "solstice_gift_membership" USING btree ("purchaserUserId");--> statement-breakpoint
CREATE INDEX "gift_membership_status_idx" ON "solstice_gift_membership" USING btree ("status");--> statement-breakpoint
CREATE INDEX "referral_referrer_idx" ON "solstice_referral" USING btree ("referrerId");--> statement-breakpoint
CREATE INDEX "referral_referred_user_idx" ON "solstice_referral" USING btree ("referredUserId");--> statement-breakpoint
CREATE INDEX "referral_status_idx" ON "solstice_referral" USING btree ("status");