CREATE TABLE "solstice_event_registration" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_event_registration_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pageSlug" text NOT NULL,
	"userId" text,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text NOT NULL,
	"status" text DEFAULT 'registered' NOT NULL,
	"notes" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "solstice_event_registration" ADD CONSTRAINT "solstice_event_registration_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "event_reg_slug_idx" ON "solstice_event_registration" USING btree ("pageSlug");--> statement-breakpoint
CREATE INDEX "event_reg_email_idx" ON "solstice_event_registration" USING btree ("email");--> statement-breakpoint
CREATE INDEX "event_reg_status_idx" ON "solstice_event_registration" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "event_reg_slug_email_idx" ON "solstice_event_registration" USING btree ("pageSlug","email");