CREATE TABLE "solstice_practice_reminder" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "solstice_practice_reminder_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"type" text NOT NULL,
	"channel" text NOT NULL,
	"sentAt" timestamp with time zone NOT NULL,
	"notes" text
);
--> statement-breakpoint
ALTER TABLE "solstice_practice_reminder" ADD CONSTRAINT "solstice_practice_reminder_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "practice_reminder_user_idx" ON "solstice_practice_reminder" USING btree ("userId","sentAt");