// Creates the newsletter-issue table (newsletters sent from /instructor/subscribers). Additive
// and safe to re-run; there is nothing to import.
import postgres from "postgres";

const TABLES = `
CREATE TABLE IF NOT EXISTS "solstice_newsletter_issue" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "subject" jsonb NOT NULL,
  "body" jsonb NOT NULL,
  "recipients" integer NOT NULL DEFAULT 0,
  "failed" integer NOT NULL DEFAULT 0,
  "sentAt" timestamptz,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);
`;

if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is not set");
const conn = postgres(process.env.DATABASE_URL, { max: 1, onnotice: () => {} });
try {
  await conn.unsafe(TABLES);
  console.log("Newsletter ready: solstice_newsletter_issue.");
} finally {
  await conn.end();
}
