// Creates the checkout, payment and payment-event tables used by the payment flow, and gives
// plans a price per currency (13b), and adds manual renewal (13c: renewal checkouts, reminder
// tracking). Additive and safe to re-run; existing plans get their one price recorded under the
// site currency.
import postgres from "postgres";

const TABLES = `
CREATE TABLE IF NOT EXISTS "solstice_checkout" (
  "id" text PRIMARY KEY,
  "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "planId" text NOT NULL,
  "provider" text NOT NULL,
  "amount" numeric(14, 2) NOT NULL,
  "currency" text NOT NULL,
  "intervalMonths" integer NOT NULL,
  "trialDays" integer NOT NULL DEFAULT 0,
  "status" text NOT NULL DEFAULT 'open',
  "providerReference" text,
  "locale" varchar(8) NOT NULL,
  "nextPath" text NOT NULL DEFAULT '/practices',
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "completedAt" timestamptz
);
CREATE INDEX IF NOT EXISTS "checkout_user_idx" ON "solstice_checkout" ("userId", "createdAt");

CREATE TABLE IF NOT EXISTS "solstice_payment" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "userId" text REFERENCES "user"("id") ON DELETE SET NULL,
  "email" text NOT NULL,
  "checkoutId" text,
  "provider" text NOT NULL,
  "providerPaymentId" text NOT NULL,
  "planId" text NOT NULL,
  "kind" text NOT NULL,
  "amount" numeric(14, 2) NOT NULL,
  "currency" text NOT NULL,
  "status" text NOT NULL DEFAULT 'paid',
  "refundedAmount" numeric(14, 2) NOT NULL DEFAULT 0,
  "periodStart" timestamptz NOT NULL,
  "periodEnd" timestamptz NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "refundedAt" timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS "payment_provider_ref_idx" ON "solstice_payment" ("provider", "providerPaymentId");
CREATE INDEX IF NOT EXISTS "payment_user_idx" ON "solstice_payment" ("userId", "createdAt");
CREATE INDEX IF NOT EXISTS "payment_created_idx" ON "solstice_payment" ("createdAt");

CREATE TABLE IF NOT EXISTS "solstice_payment_event" (
  "provider" text NOT NULL,
  "eventId" text NOT NULL,
  "type" text NOT NULL,
  "payload" jsonb NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("provider", "eventId")
);

ALTER TABLE "solstice_checkout" ADD COLUMN IF NOT EXISTS "renewal" boolean NOT NULL DEFAULT false;
ALTER TABLE "solstice_membership" ADD COLUMN IF NOT EXISTS "renewalReminderFor" timestamptz;

ALTER TABLE "solstice_membership_plan" ADD COLUMN IF NOT EXISTS "prices" jsonb NOT NULL DEFAULT '{}'::jsonb;
UPDATE "solstice_membership_plan" p
SET "prices" = jsonb_build_object(
  coalesce((SELECT s."value"->>'currency' FROM "solstice_setting" s WHERE s."key" = 'billing'), 'USD'),
  p."price"
)
WHERE p."prices" = '{}'::jsonb;
`;

if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is not set");
const conn = postgres(process.env.DATABASE_URL, { max: 1, onnotice: () => {} });
try {
  await conn.unsafe(TABLES);
  console.log("Payment tables ready: solstice_checkout, solstice_payment, solstice_payment_event; plan prices per currency.");
} finally {
  await conn.end();
}
