// Creates the checkout, payment and payment-event tables used by the payment flow. Additive and
// safe to re-run; nothing is imported (test-mode memberships never charged anything).
import postgres from "postgres";

const TABLES = `
CREATE TABLE IF NOT EXISTS "solstice_checkout" (
  "id" text PRIMARY KEY,
  "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "planId" text NOT NULL,
  "provider" text NOT NULL,
  "amount" numeric(14, 2) NOT NULL,
  "currency" text NOT NULL,
  "intervalMonths" integer NOT NULL,
  "trialDays" integer NOT NULL DEFAULT 0,
  "status" text NOT NULL DEFAULT 'open',
  "providerReference" text,
  "locale" varchar(8) NOT NULL,
  "nextPath" text NOT NULL DEFAULT '/practices',
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "completedAt" timestamptz
);
CREATE INDEX IF NOT EXISTS "checkout_user_idx" ON "solstice_checkout" ("userId", "createdAt");

CREATE TABLE IF NOT EXISTS "solstice_payment" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "userId" text REFERENCES "user"("id") ON DELETE SET NULL,
  "email" text NOT NULL,
  "checkoutId" text,
  "provider" text NOT NULL,
  "providerPaymentId" text NOT NULL,
  "planId" text NOT NULL,
  "kind" text NOT NULL,
  "amount" numeric(14, 2) NOT NULL,
  "currency" text NOT NULL,
  "status" text NOT NULL DEFAULT 'paid',
  "refundedAmount" numeric(14, 2) NOT NULL DEFAULT 0,
  "periodStart" timestamptz NOT NULL,
  "periodEnd" timestamptz NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "refundedAt" timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS "payment_provider_ref_idx" ON "solstice_payment" ("provider", "providerPaymentId");
CREATE INDEX IF NOT EXISTS "payment_user_idx" ON "solstice_payment" ("userId", "createdAt");
CREATE INDEX IF NOT EXISTS "payment_created_idx" ON "solstice_payment" ("createdAt");

CREATE TABLE IF NOT EXISTS "solstice_payment_event" (
  "provider" text NOT NULL,
  "eventId" text NOT NULL,
  "type" text NOT NULL,
  "payload" jsonb NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("provider", "eventId")
);
`;

if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is not set");
const conn = postgres(process.env.DATABASE_URL, { max: 1, onnotice: () => {} });
try {
  await conn.unsafe(TABLES);
  console.log("Payment tables ready: solstice_checkout, solstice_payment, solstice_payment_event.");
} finally {
  await conn.end();
}
